apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-henvendelse-api-proxy
  namespace: teamnks
  labels:
    team: teamnks
spec:
  image: {{ image }}
  port: 8080
  webproxy: true
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  preStopHook:
    http:
      path: /internal/stop
      port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/sf-henvendelse-api-proxy/teamnks
  ingresses:
    - "https://sf-henvendelse-api-proxy.dev.intern.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - azp_name
          - NAVident
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: itestapp
          namespace: teamcrm
        - application: gosys-q1
          namespace: isa
        - application: gosys-q2
          namespace: isa
        - application: modia-robot-api
          namespace: personoversikt
        - application: modiapersonoversikt-api-q1
          namespace: personoversikt
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
  env:
    - name: CONTEXT
      value: 'DEV'
    - name: SF_TOKENHOST
      value: 'https://test.salesforce.com/services/oauth2/token'
    - name: AUDIENCE_TOKEN_SERVICE_URL
      value: 'https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration'
    - name: AUDIENCE_TOKEN_SERVICE_ALIAS
      value: 'https://security-token-service.nais.preprod.local'
    - name: AUDIENCE_TOKEN_SERVICE
      value: 'srvhenvendelsedialog,srvmodiabrukerdialog,srvModiabrukerdialog'
    - name: SALESFORCE_AZURE_ALIAS
      value: dev-external.teamcrm.salesforce
