apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-henvendelse-api-proxy
  namespace: teamnks
  labels:
    team: teamnks
spec:
  image: '{{ image }}'
  port: 8080
  webproxy: true
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  terminationGracePeriodSeconds: 60
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - "https://sf-henvendelse-api-proxy.dev.intern.nav.no"
    - "https://sf-henvendelse-api-proxy.dev-fss-pub.nais.io"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - azp_name
          - NAVident
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: itestapp
          namespace: teamcrm
        - application: itestapp
          namespace: teamcrm
          cluster: dev-gcp
        - application: gosys-q1
          namespace: isa
        - application: gosys-q2
          namespace: isa
        - application: modia-robot-api
          namespace: personoversikt
        - application: modiapersonoversikt-api-q1
          namespace: personoversikt
        - application: azure-token-generator
          cluster: dev-gcp
          namespace: aura
        - application: pensjon-pen-q0
          namespace: pensjon-q0
        - application: pensjon-pen-q1
          namespace: pensjon-q1
        - application: pensjon-pen-q2
          namespace: pensjon-q2
        - application: pensjon-pen-q5
          namespace: pensjon-q5
        - application: bisys
          namespace: bidrag
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
        - application: modiapersonoversikt-api
          namespace: personoversikt
          cluster: dev-gcp
  envFrom:
    - secret: sf-henvendelse-api
  env:
    - name: TWINCALL # TWINCALL ON triggers two calls and returns the fastest response
      value: 'ON'
    - name: SF_TOKENHOST
      value: 'https://test.salesforce.com/services/oauth2/token'
    - name: AUDIENCE_TOKEN_SERVICE_URL
      value: 'https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration'
    - name: AUDIENCE_TOKEN_SERVICE_ALIAS
      value: 'https://security-token-service.nais.preprod.local'
    - name: AUDIENCE_TOKEN_SERVICE
      value: 'srvhenvendelsedialog,srvmodiabrukerdialog,srvModiabrukerdialog'
    - name: SALESFORCE_AZURE_ALIAS
      value: dev-external.teamcrm.salesforce
    - name: DEPLOY_CLUSTER
      value: '{{ DEPLOY_CLUSTER }}'
