apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-henvendelse-api-proxy
  namespace: teamnks
  labels:
    team: teamnks
spec:
  image: {{ image }}
  port: 8080
  webproxy: true
  replicas:
    min: 12
    max: 12
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  preStopHook:
    exec:
      command: [ "/bin/bash", "/pre-stop.sh" ]
  terminationGracePeriodSeconds: 60
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 200m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/sf-henvendelse-api-proxy/teamnks
  ingresses:
    - "https://sf-henvendelse-api-proxy.intern.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - azp_name
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: itestapp
          namespace: teamcrm
        - application: gosys
          namespace: isa
        - application: modia-robot-api
          namespace: personoversikt
        - application: modiapersonoversikt-api
          namespace: personoversikt
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
  env:
    - name: CONTEXT
      value: 'PROD'
    - name: TWINCALL # TWINCALL triggers two calls and returns the fastest response
      value: 'OFF'
    - name: SF_TOKENHOST
      value: 'https://login.salesforce.com/services/oauth2/token'
    - name: AUDIENCE_TOKEN_SERVICE_URL
      value: 'https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration'
    - name: AUDIENCE_TOKEN_SERVICE_ALIAS
      value: 'https://security-token-service.nais.adeo.no'
    - name: AUDIENCE_TOKEN_SERVICE
      value: 'srvhenvendelsedialog,srvmodiabrukerdialog,srvModiabrukerdialog'
    - name: SALESFORCE_AZURE_ALIAS
      value: prod-external.teamcrm.salesforce
