# copied from
# https://sikkerhet.nav.no/docs/verktoy/dependabot#oppsett-gradle-buildgradlekts--buildgradle

name: Monitor dependencies with Dependabot
on:
  push:
    branches:
      - dependy
    # disregard paths for now
    #paths:
    #  - "**.gradle.kts"
    #  - "gradle.properties"
  # workflow_dispatch is not relevant until we put this in master
  #workflow_dispatch:
jobs:
  dependabot:
    name: Monitor dependencies with Dependabot
    runs-on: ubuntu-20.04
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v3 # ratchet:actions/checkout@v3
      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          fail-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
