name: Build, push, deploy fss and gcp

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Build and run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew test
  build:
    name: Build and push Docker container
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true
          dependency-graph: generate-and-submit
      - name: Build JAR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build shadowJar -x test
      - name: Build and publish Docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamnks
  deploy-dev-fss:
    name: Deploy to NAIS dev fss
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/dev-fss.yaml
          VAR: image=${{ needs.build.outputs.image }},DEPLOY_CLUSTER=dev-fss
  deploy-dev-gcp:
    name: Deploy to NAIS dev gcp
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-gcp.yaml
          VAR: image=${{ needs.build.outputs.image }},DEPLOY_CLUSTER=dev-gcp
#  deploy-prod-fss:
#    name: Deploy to NAIS prod fss
#    needs: build
#    if: github.ref == 'refs/heads/master'
#    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#      contents: read
#    steps:
#      - uses: actions/checkout@v4
#      - uses: nais/deploy/actions/deploy@v2
#        env:
#          CLUSTER: prod-fss
#          RESOURCE: .nais/prod-fss.yaml
#          VAR: image=${{ needs.build.outputs.image }},DEPLOY_CLUSTER=prod-fss
#  deploy-prod-gcp:
#    name: Deploy to NAIS prod gcp
#    needs: build
#    if: github.ref == 'refs/heads/master'
#    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#      contents: read
#    steps:
#      - uses: actions/checkout@v4
#      - uses: nais/deploy/actions/deploy@v2
#        env:
#          CLUSTER: prod-gcp
#          RESOURCE: .nais/prod-gcp.yaml
#          VAR: image=${{ needs.build.outputs.image }},DEPLOY_CLUSTER=prod-gcp
